export type TabId = "all" | "shiv" | "gita" | "veda" | "buddha" | "christ" | "quran" | "jain" | "sikh" | "torah" | "tao";

export interface TabConfig {
  id: TabId;
  name: string;
  domain: string;
  symbol: string;
  tagline: string;
  subtitle: string;
  placeholder: string;
  buttonLabel: string;
  footerMantra: string;
  footerText: string;
  exploreLabel: string;
  chatSubtitle: string;
  inputPlaceholder: string;
  sourceLine: string;
  color: string;
}

export const TABS: Record<TabId, TabConfig> = {
  all: {
    id: "all",
    name: "Happiness",
    domain: "shiv.ai",
    symbol: "✦",
    tagline: "Ancient Wisdom for a Happy Life",
    subtitle: "Every great tradition began with one purpose — to help us find happiness, love one another, and live a meaningful life. That wisdom is more relevant today than ever.",
    placeholder: "What’s on your mind? Share what you’re going through and receive wisdom from 3,500+ years of human understanding...",
    buttonLabel: "Find My Wisdom",
    footerMantra: "✦ All paths lead to one truth: happiness lives within ✦",
    footerText: "Drawing from 11 spiritual traditions, 3,500+ years of wisdom — because every religion started with the same beautiful idea: that humans should be happy",
    exploreLabel: "What are you seeking?",
    chatSubtitle: "Personalized wisdom from every tradition for your happiness",
    inputPlaceholder: "Share what you’re struggling with — anxiety, grief, purpose, relationships...",
    sourceLine: "Source: Combined Wisdom of All Sacred Traditions",
    color: "#F59E0B",
  },
  shiv: {
    id: "shiv",
    name: "Shiva",
    domain: "shiv.ai",
    symbol: "ॐ",
    tagline: "Find Peace Through the Wisdom of Shiva",
    subtitle: "Shiva teaches us that transformation is the path to happiness — every ending is a new beginning",
    placeholder: "What’s troubling your mind? Let Shiva’s wisdom guide you to inner peace...",
    buttonLabel: "Seek Peace",
    footerMantra: "ॐ Namah Shivaya — I honor the divine within 🔱",
    footerText: "Shiva’s wisdom: True happiness is found in stillness, transformation, and letting go",
    exploreLabel: "Explore Shiva’s Path to Happiness",
    chatSubtitle: "Find peace and transformation through Shiva’s wisdom",
    inputPlaceholder: "Ask anything — Shiva’s wisdom for your peace of mind...",
    sourceLine: "Sources: Shiv Purana, Vigyan Bhairav Tantra, Shiva Sutras",
    color: "#FF6B00",
  },
  gita: {
    id: "gita",
    name: "Gita",
    domain: "gita.ai",
    symbol: "🕉️",
    tagline: "Find Purpose Through Krishna’s Timeless Wisdom",
    subtitle: "The Gita teaches us that lasting happiness comes from doing our duty without attachment to results",
    placeholder: "Feeling lost or anxious? Let Krishna’s words guide you to clarity and purpose...",
    buttonLabel: "Find Purpose",
    footerMantra: "धर्मक्षेत्रे कुरुक्षेत्रे — Where there is dharma, there is victory 📖",
    footerText: "Krishna’s wisdom: Act with love, let go of results, and find joy in the journey itself",
    exploreLabel: "Explore the Gita’s Path to Happiness",
    chatSubtitle: "Find purpose and peace through Krishna’s teachings",
    inputPlaceholder: "Ask anything — Krishna’s wisdom for your life...",
    sourceLine: "Source: Bhagavad Gita, 18 Chapters, 700 Verses",
    color: "#E6A817",
  },
  veda: {
    id: "veda",
    name: "Vedas",
    domain: "veda.ai",
    symbol: "📜",
    tagline: "Discover Joy Through the World’s Oldest Wisdom",
    subtitle: "The Vedas reveal that bliss is not something you seek — it is what you already are",
    placeholder: "Seeking deeper meaning? The Vedas hold 5,000 years of wisdom about true happiness...",
    buttonLabel: "Discover Joy",
    footerMantra: "Tat Tvam Asi — You Are That 🌿",
    footerText: "Vedic wisdom: The universe is made of bliss — you are born from joy and to joy you return",
    exploreLabel: "Explore the Vedic Path to Happiness",
    chatSubtitle: "Discover the joy that is your true nature",
    inputPlaceholder: "Ask anything — powered by 5,000 years of Vedic wisdom...",
    sourceLine: "Sources: Rig Veda, Upanishads, Vedanta",
    color: "#7B68EE",
  },
  buddha: {
    id: "buddha",
    name: "Buddha",
    domain: "buddha.ai",
    symbol: "☸️",
    tagline: "End Suffering, Begin Living — The Buddhist Way",
    subtitle: "The Buddha showed that suffering has a cause, and therefore a cure — happiness is a skill you can learn",
    placeholder: "Feeling anxious or restless? The Buddha’s path leads from suffering to lasting peace...",
    buttonLabel: "Find Peace",
    footerMantra: "May all beings be happy, may all beings be free ☸️",
    footerText: "Buddha’s wisdom: Happiness is not something readymade — it comes from your own actions",
    exploreLabel: "Explore the Buddhist Path to Happiness",
    chatSubtitle: "Learn the art of happiness through Buddhist wisdom",
    inputPlaceholder: "Ask anything — wisdom for ending suffering and finding joy...",
    sourceLine: "Sources: Dhammapada, Heart Sutra, Sutta Pitaka",
    color: "#D4A017",
  },
  christ: {
    id: "christ",
    name: "Christ",
    domain: "christ.ai",
    symbol: "✝️",
    tagline: "Find Rest for Your Soul — Through Love and Grace",
    subtitle: "Jesus taught that love is the greatest commandment — and in loving others, we find our deepest happiness",
    placeholder: "Feeling weary or burdened? Jesus said ‘Come to me and I will give you rest’...",
    buttonLabel: "Find Rest",
    footerMantra: "Love one another as I have loved you ✝️",
    footerText: "Christ’s wisdom: The greatest of these is love — and perfect love casts out all fear",
    exploreLabel: "Explore Christ’s Path to Happiness",
    chatSubtitle: "Find love, hope, and rest through Christ’s teachings",
    inputPlaceholder: "Ask anything — wisdom of love and grace for your life...",
    sourceLine: "Sources: Holy Bible, Teachings of Jesus, Psalms & Proverbs",
    color: "#4169E1",
  },
  quran: {
    id: "quran",
    name: "Quran",
    domain: "quran.ai",
    symbol: "☪️",
    tagline: "Find Tranquility Through Divine Remembrance",
    subtitle: "The Quran teaches that in the remembrance of God, hearts find peace — and with every hardship comes relief",
    placeholder: "Feeling troubled? The Quran says ‘with every hardship there is relief’...",
    buttonLabel: "Find Tranquility",
    footerMantra: "Bismillah ir-Rahman ir-Rahim — In the name of God, Most Gracious, Most Merciful ☪️",
    footerText: "Quranic wisdom: God does not burden a soul beyond what it can bear",
    exploreLabel: "Explore the Quran’s Path to Happiness",
    chatSubtitle: "Find mercy, peace, and guidance through Quranic wisdom",
    inputPlaceholder: "Ask anything — wisdom of peace and mercy for your life...",
    sourceLine: "Sources: Holy Quran, Hadith, Islamic Wisdom",
    color: "#2E8B57",
  },
  jain: {
    id: "jain",
    name: "Jain",
    domain: "jain.ai",
    symbol: "🕉️",
    tagline: "Find Liberation Through Compassion and Non-Violence",
    subtitle: "Jain wisdom teaches that happiness flows from compassion — when we stop harming, we start healing",
    placeholder: "Seeking inner freedom? Jain wisdom shows how compassion leads to true liberation...",
    buttonLabel: "Find Freedom",
    footerMantra: "Parasparopagraho Jivanam — All life is interconnected 🕉️",
    footerText: "Jain wisdom: The soul is already perfect — shed what obscures your happiness",
    exploreLabel: "Explore the Jain Path to Happiness",
    chatSubtitle: "Find liberation through compassion and truth",
    inputPlaceholder: "Ask anything — Jain wisdom for your inner freedom...",
    sourceLine: "Sources: Agamas, Tattvartha Sutra, Mahavira’s Teachings",
    color: "#FF4500",
  },
  sikh: {
    id: "sikh",
    name: "Sikh",
    domain: "shiv.ai",
    symbol: "🙏",
    tagline: "Find Equality and Joy in the One Creator",
    subtitle: "Sikh wisdom teaches that true happiness is found within — not in wealth, status, or the outside world",
    placeholder: "Searching for inner peace? Guru Nanak said ‘happiness is an inside job’...",
    buttonLabel: "Find Joy",
    footerMantra: "❤️ Waheguru — The One who takes us from darkness to light ❤️",
    footerText: "Sikh wisdom: Even kings cannot compare with an ant filled with the love of God",
    exploreLabel: "Explore the Sikh Path to Happiness",
    chatSubtitle: "Find equality, devotion, and joy through Guru’s wisdom",
    inputPlaceholder: "Ask anything — Sikh wisdom for your happiness...",
    sourceLine: "Sources: Guru Granth Sahib, Ten Gurus, Sikh Philosophy",
    color: "#FF6B00",
  },
  torah: {
    id: "torah",
    name: "Torah",
    domain: "shiv.ai",
    symbol: "✡",
    tagline: "Choose Life — 3,500 Years of Wisdom for Living Well",
    subtitle: "Jewish wisdom teaches that every person is an entire universe — and happiness comes from choosing life, justice, and mercy",
    placeholder: "Feeling overwhelmed? The Psalms say ‘Be still, and know’ — ancient peace for modern anxiety...",
    buttonLabel: "Choose Life",
    footerMantra: "✡️ Shema Yisrael — Hear, O Israel: the truth is One ✡️",
    footerText: "Torah wisdom: Weeping may endure for a night, but joy comes in the morning",
    exploreLabel: "Explore the Torah’s Path to Happiness",
    chatSubtitle: "Find wisdom, justice, and joy in Jewish teachings",
    inputPlaceholder: "Ask anything — 3,500 years of wisdom for your life...",
    sourceLine: "Sources: Torah, Talmud, Psalms, Pirkei Avot",
    color: "#1E40AF",
  },
  tao: {
    id: "tao",
    name: "Tao",
    domain: "shiv.ai",
    symbol: "☯",
    tagline: "Flow Like Water — The Art of Effortless Living",
    subtitle: "Taoist wisdom teaches that happiness comes not from striving but from flowing — like water finding its way",
    placeholder: "Trying too hard? Lao Tzu said ‘the highest good is like water’ — find your natural flow...",
    buttonLabel: "Find Flow",
    footerMantra: "☯ The Tao that can be told is not the eternal Tao ☯",
    footerText: "Taoist wisdom: Knowing yourself is true wisdom — mastering yourself is true power",
    exploreLabel: "Explore the Tao’s Path to Happiness",
    chatSubtitle: "Find harmony and flow through Taoist wisdom",
    inputPlaceholder: "Ask anything — Taoist wisdom for finding your natural flow...",
    sourceLine: "Sources: Tao Te Ching, Zhuangzi, I Ching, Analects",
    color: "#047857",
  },
};

export function getTabConfig(tab: TabId): TabConfig {
  return TABS[tab];
}
